/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsCategoryIdRouteImport } from './routes/results.$categoryId'
import { Route as QuizCategoryIdRouteImport } from './routes/quiz.$categoryId'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsCategoryIdRoute = ResultsCategoryIdRouteImport.update({
  id: '/results/$categoryId',
  path: '/results/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizCategoryIdRoute = QuizCategoryIdRouteImport.update({
  id: '/quiz/$categoryId',
  path: '/quiz/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/todos': typeof TodosRoute
  '/quiz/$categoryId': typeof QuizCategoryIdRoute
  '/results/$categoryId': typeof ResultsCategoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/todos': typeof TodosRoute
  '/quiz/$categoryId': typeof QuizCategoryIdRoute
  '/results/$categoryId': typeof ResultsCategoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/todos': typeof TodosRoute
  '/quiz/$categoryId': typeof QuizCategoryIdRoute
  '/results/$categoryId': typeof ResultsCategoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/todos' | '/quiz/$categoryId' | '/results/$categoryId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/todos' | '/quiz/$categoryId' | '/results/$categoryId'
  id: '__root__' | '/' | '/todos' | '/quiz/$categoryId' | '/results/$categoryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TodosRoute: typeof TodosRoute
  QuizCategoryIdRoute: typeof QuizCategoryIdRoute
  ResultsCategoryIdRoute: typeof ResultsCategoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$categoryId': {
      id: '/results/$categoryId'
      path: '/results/$categoryId'
      fullPath: '/results/$categoryId'
      preLoaderRoute: typeof ResultsCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$categoryId': {
      id: '/quiz/$categoryId'
      path: '/quiz/$categoryId'
      fullPath: '/quiz/$categoryId'
      preLoaderRoute: typeof QuizCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TodosRoute: TodosRoute,
  QuizCategoryIdRoute: QuizCategoryIdRoute,
  ResultsCategoryIdRoute: ResultsCategoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
